# For full config options, check the docs:
#    docs.serverless.com

service: todo-api

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: eu-west-1
  deploymentBucket:
    name: s3-serverless-deployment-bucket  # Need ti be created on S3

  environment:
    ENV: ${self:custom.environment.ENV}
    REGION: ${self:custom.environment.REGION}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
        - lambda:InvokeAsync
      Resource: "*"

plugins:
  - serverless-plugin-typescript
  - serverless-offline # serverless-offline needs to be last in the list

package:
  individually: false
  exclude:
    - tests/**

functions:
  list-todo:
    handler: src/index.listTodo
    timeout: 12
    events:
      - http:
          path: /todos
          method: get
          cors:
            origin: "*"
            headers: ${self:custom.allowedHeaders}
            allowCredentials: true

custom:
  stage: ${opt:stage, self:provider.stage}
  environment: ${file(../env.yml):${self:custom.stage}, file(../env.yml):dev}
  allowedHeaders:
    - Accept
    - Content-Type
    - X-Amz-Date
    - Date
    - Authorization
    - X-Api-Key
    - X-Amz-Security-Token
    - X-Amz-User-Agent
    - X-Staytuned-Origin

